name: 'CI/CD: build, test and deploy using github registry and nomad'
description: 'Builds docker image, pushes to github registry, tests, deploys to nomad cluster'
author: internetarchive
branding:
  icon: 'globe'
  color: 'white'

runs:
  using: "composite"

  steps:
    # https://github.com/internetarchive/build/blob/main/action.yml
    - name: build
      uses: internetarchive/build@v1
      with:
        REGISTRY_TOKEN: ${{ inputs.REGISTRY_TOKEN }}

    # https://github.com/internetarchive/test/blob/main/action.yml
    - name: test
      uses: internetarchive/test@v1
      with:
        TEST_SCRIPT: ${{ inputs.TEST_SCRIPT }}

    # https://github.com/internetarchive/deploy/blob/main/action.yml
    - name: deploy
      uses: internetarchive/deploy@v1
      with:
        BASE_DOMAIN: ${{ inputs.BASE_DOMAIN }}
        NOMAD_ADDR: ${{ inputs.NOMAD_ADDR }}
        NOMAD_TOKEN: ${{ inputs.NOMAD_TOKEN }}
        NOMAD_TOKEN_PROD: ${{ inputs.NOMAD_TOKEN_PROD }}
        REGISTRY_TOKEN: ${{ inputs.REGISTRY_TOKEN }}
        NOMAD_VAR_CHECK_PATH: ${{ inputs.NOMAD_VAR_CHECK_PATH }}
        NOMAD_VAR_CHECK_PROTOCOL: ${{ inputs.NOMAD_VAR_CHECK_PROTOCOL }}
        NOMAD_VAR_CHECK_TIMEOUT: ${{ inputs.NOMAD_VAR_CHECK_TIMEOUT }}
        NOMAD_VAR_COUNT: ${{ inputs.NOMAD_VAR_COUNT }}
        NOMAD_VAR_CPU: ${{ inputs.NOMAD_VAR_CPU }}
        NOMAD_VAR_HEALTH_TIMEOUT: ${{ inputs.NOMAD_VAR_HEALTH_TIMEOUT }}
        NOMAD_VAR_HOME: ${{ inputs.NOMAD_VAR_HOME }}
        NOMAD_VAR_HOSTNAMES: ${{ inputs.NOMAD_VAR_HOSTNAMES }}
        NOMAD_VAR_MEMORY: ${{ inputs.NOMAD_VAR_MEMORY }}
        NOMAD_VAR_NO_DEPLOY: ${{ inputs.NOMAD_VAR_NO_DEPLOY }}
        NOMAD_VAR_PG: ${{ inputs.NOMAD_VAR_PG }}
        NOMAD_VAR_PORTS: ${{ inputs.NOMAD_VAR_PORTS }}
        NOMAD_VAR_PV: ${{ inputs.NOMAD_VAR_PV }}
        NOMAD_VAR_PV_DB: ${{ inputs.NOMAD_VAR_PV_DB }}

inputs:
  BASE_DOMAIN:
    description: 'nomad cluster wildcard DNS domain name, eg: example.com'
    required: true

  NOMAD_ADDR:
    description: 'nomad cluster API endpoint - archive.org deploys automate this but you can override'
    required: false

  NOMAD_TOKEN:
    description: 'nomad cluster credentials - store in your repo GitHub Secrets'
    required: true

  NOMAD_TOKEN_PROD:
    description: 'nomad archive.org production cluster credentials - store in your repo GitHub Secrets'
    default: ''
    required: false

  REGISTRY_TOKEN:
    description: 'for registry'
    required: true

  TEST_SCRIPT:
    description: 'default looks for [WORKDIR]/test.sh in docker image and runs it.  pass in alt pathname'
    default: './test.sh'
    required: false


  NOMAD_VAR_CHECK_PATH:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CHECK_PROTOCOL:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CHECK_TIMEOUT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_COUNT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CPU:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HEALTH_TIMEOUT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HOME:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HOSTNAMES:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_MEMORY:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_NO_DEPLOY:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PG:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PORTS:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PV:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PV_DB:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false
